Document: libtenma
Title: Debian libtenma Manual
Author: <insert document author here>
Abstract: This manual describes what libtenma is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libtenma/libtenma.sgml.gz

Format: postscript
Files: /usr/share/doc/libtenma/libtenma.ps.gz

Format: text
Files: /usr/share/doc/libtenma/libtenma.text.gz

Format: HTML
Index: /usr/share/doc/libtenma/html/index.html
Files: /usr/share/doc/libtenma/html/*.html
